In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
Df=pd.read_excel(r"C:\Users\sagar\OneDrive\Desktop\vaishu\Dataset\zomato.xlsx")

In [5]:
Df.dropna(subset=['name'], inplace=True)
Df=Df.dropna(subset=['location'])
Df=Df.drop(columns=['phone'])
Df=Df.dropna(subset=['rest_type'])
Df=Df.dropna(subset=['cuisines'])
Df=Df.dropna(subset=['approx_cost(for two people)'])
Df=Df.dropna(subset=['dish_liked'])

In [33]:
Df.isnull().sum()

name                            0
online_order                    0
book_table                      0
rate                           29
votes                           0
location                        0
rest_type                       0
dish_liked                      0
cuisines                        0
approx_cost(for two people)     0
dtype: int64

In [34]:
Df = Df[Df['online_order'].isin(['Yes', 'No'])]

In [18]:
Df.tail(30)

,name,online_order,book_table,rate,votes,location,rest_type,dish_liked,cuisines,approx_cost(for two people)
55943,Red Rhino,Yes,Yes,4.4 /5,1980,Whitefield,"Microbrewery, Pub","Beer, Margarita, Long Island Iced Tea, Cocktai...","Continental, Mediterranean, South Indian, Nort...",1700
55945,Ji Hazoor,Yes,Yes,4.0 /5,2856,Whitefield,"Casual Dining, Bar","Chicken Salad, Mocktails, Mutton Curry, Chicke...","Mughlai, North Indian, Biryani, Afghan",1100
55946,HQ,No,Yes,4.1 /5,564,Whitefield,"Casual Dining, Bar","Mocktails, Pizza, Crispy Chicken, Beer, Nachos...","North Indian, Italian, Finger Food, Continental",1000
55948,Biere Societee,No,Yes,4.2 /5,320,Whitefield,Pub,"Tempura Prawns, Cocktails, Noodles, Masala Pea...","Asian, Continental, European",1500
55949,Uno Chicago Bar & Grill,No,Yes,4.2 /5,156,Whitefield,"Bar, Casual Dining","Deep Dish Pizza, Mocktails, Burgers, Onion Rin...","American, Italian",1800
55950,Amoeba Sports Bar,Yes,Yes,3.9 /5,578,Whitefield,"Lounge, Bar","Pasta, Fish, Beer, Chicken Wings, Mocktails, G...","Continental, Chinese",1000
55951,One For The Road,Yes,Yes,4.1 /5,137,Whitefield,Bar,"Cocktails, Pasta, Fish","Continental, North Indian, Finger Food",1200
55952,Whitefield Social,Yes,No,4.1 /5,2773,Whitefield,Pub,"Cocktails, Chicken Kebab, Murgh Ghee Roast, Vi...","American, North Indian, Chinese, Finger Food, ...",1500
55954,The Whitefield Arms Pub & Microbrewery,Yes,Yes,4.2 /5,1113,Whitefield,"Pub, Microbrewery","Beer, Chicken Tikka, Cosmopolitan, Burgers, Co...","British, Continental, BBQ",1600
55956,The Irish House,No,Yes,4.3 /5,1776,Whitefield,"Casual Dining, Pub","Beer, Cocktails, Burgers, Chicken Nachos, Mock...","European, American",1700
55958,Shizusan Shophouse & Bar,Yes,Yes,4.4 /5,1313,Whitefield,"Casual Dining, Bar","California Roll, Cocktails, Mocktails, Maki Ro...","Asian, Japanese, Vietnamese, Korean, Chinese, ...",1800
55960,Kava Kitchen & Bar - Fairfield by Marriott,No,No,3.9 /5,74,Whitefield,"Casual Dining, Bar",Dal Halwa,"North Indian, South Indian, Continental, Ameri...",1200
55961,Harry's Bar + Cafe,Yes,Yes,4.1 /5,1218,Whitefield,Pub,"Cocktails, Beer, Long Island Iced Tea, Pasta, ...","Asian, American, Mexican",1200
55963,BAR BAR,No,Yes,4.1 /5,1003,Whitefield,"Bar, Casual Dining","Mocktails, Cocktails, Pizza, Chicken Tikka, Na...","Continental, North Indian, Italian",1500
55965,The Beer Cafe,Yes,Yes,4.1 /5,673,Whitefield,Pub,"Cocktails, Wheat Beer, Bruschettas, Pasta, Bur...","Finger Food, North Indian, Chinese, Italian",1400
55967,Pablo's Gastrobar,No,No,4.0 /5,1094,Whitefield,Bar,"Cocktails, Beer, Pizza, Long Island Iced Tea, ...","Finger Food, American, Asian, Italian",1450
55968,Oliver's Pub & Diner,Yes,Yes,3.9 /5,548,Whitefield,"Pub, Casual Dining","Pizza, Beer, Cocktails, Nachos, Pasta, Moo Bur...","Finger Food, American, Continental, Burger, Pizza",1500
55969,Smaaash,No,Yes,4.0 /5,189,Whitefield,"Casual Dining, Pub","Pizza, Beer","North Indian, Pizza, Chinese",1500
55970,Izakaya Gastro Pub,Yes,Yes,3.8 /5,128,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",1200
55971,Red Glow,No,No,3.7 /5,27,Whitefield,Pub,NaN,"North Indian, Continental",1200
55972,M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9 /5,77,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,2000
55973,Keys Cafe - Keys Hotel,No,No,2.8 /5,161,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",1200
55974,The Farm House Bar n Grill,No,No,3.7 /5,34,Whitefield,"Casual Dining, Bar",NaN,"North Indian, Continental",800
55975,Topsy Turvey,No,No,NaN,0,Whitefield,Bar,NaN,Finger Food,900
55976,Bhagini,No,No,2.5 /5,81,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800
55977,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,27,Whitefield,Bar,NaN,Continental,1500
55978,Vinod Bar And Restaurant,No,No,NaN,0,Whitefield,Bar,NaN,Finger Food,600
55979,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,0,Whitefield,Bar,NaN,Finger Food,2000
55980,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,2500
55981,The Nest - The Den Bengaluru,No,No,3.4 /5,13,"ITPL Main Road, Whitefield","Bar, Casual Dining",NaN,"Finger Food, North Indian, Continental",1500

In [20]:
Df['rate']=Df['rate'].str.replace('/5', '')

In [21]:
Df['rate']

0         4.1
1         4.1
2         3.8
3         3.7
4         3.8
         ...
55977    3.6
55978     NaN
55979     NaN
55980    4.3
55981    3.4
Name: rate, Length: 51148, dtype: object

In [ ]:
Df = Df.loc[Df["rate"] !='NEW']

In [ ]:
Df['rate']=Df['rate'].astype('float')

In [ ]:
Df['rate'].fillna(Df['rate'].mean(), inplace=True)

In [ ]:
Df.to_excel('ZOMATO_4.xlsx')